// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs6RToEE3pSxMrTzgvKN1SfaZnxuqaEKo',
    appId: '1:830369551905:web:9a2351da8fcd5f34807560',
    messagingSenderId: '830369551905',
    projectId: 'smart-evm-6d9a5',
    authDomain: 'smart-evm-6d9a5.firebaseapp.com',
    databaseURL: 'https://smart-evm-6d9a5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-evm-6d9a5.appspot.com',
    measurementId: 'G-GRKDYT4PYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6CaJNwf9EmcW8_KD-P_JADnZgHUKcCms',
    appId: '1:830369551905:android:bb5416952f4e6539807560',
    messagingSenderId: '830369551905',
    projectId: 'smart-evm-6d9a5',
    databaseURL: 'https://smart-evm-6d9a5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-evm-6d9a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnUTwLQJqsCJorOe2qcYaP5Olz47fAoL8',
    appId: '1:830369551905:ios:07e704002da94a84807560',
    messagingSenderId: '830369551905',
    projectId: 'smart-evm-6d9a5',
    databaseURL: 'https://smart-evm-6d9a5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-evm-6d9a5.appspot.com',
    iosBundleId: 'com.example.smartEvm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnUTwLQJqsCJorOe2qcYaP5Olz47fAoL8',
    appId: '1:830369551905:ios:07e704002da94a84807560',
    messagingSenderId: '830369551905',
    projectId: 'smart-evm-6d9a5',
    databaseURL: 'https://smart-evm-6d9a5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-evm-6d9a5.appspot.com',
    iosBundleId: 'com.example.smartEvm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCs6RToEE3pSxMrTzgvKN1SfaZnxuqaEKo',
    appId: '1:830369551905:web:3a71edbd2ba49185807560',
    messagingSenderId: '830369551905',
    projectId: 'smart-evm-6d9a5',
    authDomain: 'smart-evm-6d9a5.firebaseapp.com',
    databaseURL: 'https://smart-evm-6d9a5-default-rtdb.firebaseio.com',
    storageBucket: 'smart-evm-6d9a5.appspot.com',
    measurementId: 'G-DYHCQ03VX3',
  );
}
